name: Publish Extension (Preview)
on: [push]
jobs:
  publish-vsts-extension:
    name: Publish Extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install tfx-cli
        run:  npm i -g tfx-cli
      - name: Sync Common
        shell: pwsh
        run: |
          $Path = '/home/runner/work/vsts-btdf-tasks/vsts-btdf-tasks'
          Get-ChildItem -Path $Path -Directory -Exclude Common | ForEach-Object {
              Copy-Item -Path ([IO.Path]::Join($Path,'Common*.*') -Destination $_ -Force -Recurse
          }
      - name:
        run: tfx extension create --manifest-globs vss-extension.json --override "{\"version\":\"2.0.0\"}"
      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./*.vsix
      # - name: Publish to Visual Studio Marketplace
      #   uses: HaaLeo/publish-vscode-extension@v0
      #   with:
      #     pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
      #     registryUrl: https://marketplace.visualstudio.com
      #     extensionFile: ./*.vsix
      #     packagePath: ''
